# Generated by Django 2.2 on 2019-05-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hop',
            field=models.BooleanField(default=False, verbose_name='горячее предложение'),
        ),
    ]
